In [1]:
# this is a new test commit

In [1]:
import pandas as pd
import pathlib
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import cm

In [2]:
############################## READ ALL DATA #############################################
## WEATHER FILES ##
# AZ PHX Sky Harbor Data #
AZW_15 = pd.read_csv("./Data/Weather Data/KPHX-15.csv")
# ENVIMET DATA #
BPS = []
Fname = []
for path in pathlib.Path("./Data/BPS").iterdir():
    if path.is_file():
        current_file = pd.read_csv(path)
        BPS.append(current_file)
        Fname.append(path.name.replace('.csv', ''))

## Drop last row of EnviMet Data
for i in range(len(BPS)):
    BPS[i] = BPS[i].drop(16)

In [3]:
######################### CHOOSNG ENVI-MET BUILDING MICROCLIMATE DATA #################################

## BUILDING ##

# Interdisciplinary AB Microclimate Data
Inter_AB = pd.read_csv("./Data/Weather Data/Interdisciplinary AB 2018.csv")
Inter_AB_W = pd.DataFrame()
Inter_AB_W = Inter_AB_W.append(BPS[7])
Inter_AB_W = Inter_AB_W[['Time', 'AirTempInFrontOfAllFacades_MEAN', 'RelativeAirHumidityInFrontOfAllFacades_MEAN',
                     'WindSpeedInFrontOfAllFacades_MEAN']]

Inter_AB_W = Inter_AB_W.rename(columns = {'AirTempInFrontOfAllFacades_MEAN':'Mean Air Temp',
                                    'RelativeAirHumidityInFrontOfAllFacades_MEAN':'Mean Rel Humidity',
                                    'WindSpeedInFrontOfAllFacades_MEAN':'Mean Wind Speed'})
Inter_AB_W

           Time  Mean Air Temp  Mean Rel Humidity  Mean Wind Speed
0    5.00.00 AM      29.537667          12.699708         0.960636
1    6.00.01 AM      29.033387          16.378229         0.950390
2    7.00.01 AM      29.604562          17.250977         0.934667
3    8.00.01 AM      31.459578          16.705515         0.910811
4    9.00.01 AM      33.820584          14.477529         0.883124
5   10.00.01 AM      35.796708          10.969304         0.857149
6   11.00.01 AM      36.879628           8.902718         0.845888
7   12.00.01 PM      37.837624           7.785688         0.840698
8    1.00.01 PM      38.771101           6.989491         0.836719
9    2.00.01 PM      39.486798           6.362558         0.827031
10   3.00.01 PM      39.867346           6.021546         0.812664
11   4.00.01 PM      40.046582           5.873886         0.803412
12   5.00.01 PM      39.936800           5.854970         0.795816
13   6.00.01 PM      39.575997           5.906207         0.785057
14   7.00.01 PM      38.936188           6.200171         0.771208
15   8.00.01 PM      38.108705           6.634349         0.754144

In [4]:
########################### FORMATING BIG DATA FRAMES ##############################

## Weather file ##
AZW_15 = AZW_15.set_index('Date_Time')


## Building ##
# Inter_AB = Interdisciplinary AB Campus Metabolism Data
# Data_Inter = Inter_AB + Weather Data

##### Step 1
for i in range(len(Inter_AB)):
    Inter_AB['tstamp'][i] = (str(Inter_AB['tstamp'][i][5:7]) + '/' + str(Inter_AB['tstamp'][i][8:10]) + '/2018' + ' ' + str(Inter_AB['tstamp'][i][11:16]))
    
Inter_AB = Inter_AB[['tstamp', 'bldgname', 'KW', 'CHWTON', 'HTmmBTU']]

##### Step 2 
month = []
time = []

for i in range(len(Inter_AB)):
    month.append(Inter_AB['tstamp'][i][0:2])

for i in range(len(Inter_AB)):
    time.append((Inter_AB['tstamp'][i][11:13] + Inter_AB['tstamp'][i][14:]))

Inter_AB['month'] = month
Inter_AB['time'] = time


##### Step 3
Inter_AB = Inter_AB.set_index('tstamp')


##### Step 4
Data_Inter =  pd.concat([Inter_AB, AZW_15], axis=1, join="inner")
Data_Inter = Data_Inter[['month', 'time', 'bldgname', 'KW', 'CHWTON', 'HTmmBTU', 'Air Temp', 'Rel Humid']]

<ipython-input-4-24a3bb3194af>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Inter_AB['tstamp'][i] = (str(Inter_AB['tstamp'][i][5:7]) + '/' + str(Inter_AB['tstamp'][i][8:10]) + '/2018' + ' ' + str(Inter_AB['tstamp'][i][11:16]))

In [5]:
######################## DATA FORMATTING for JUNE 9 ##########################

time = []
time.append('0500')
time.append('0600')
time.append('0700')
time.append('0800')
time.append('0900')
time.append('1000')
time.append('1100')
time.append('1200')
time.append('1300')
time.append('1400')
time.append('1500')
time.append('1600')
time.append('1700')
time.append('1800')
time.append('1900')
time.append('2000')

month = []
for i in range(16):
    month.append('06')

date = []
date.append('06/09/2018 05:00')
date.append('06/09/2018 06:00')
date.append('06/09/2018 07:00')
date.append('06/09/2018 08:00')
date.append('06/09/2018 09:00')
date.append('06/09/2018 10:00')
date.append('06/09/2018 11:00')
date.append('06/09/2018 12:00')
date.append('06/09/2018 13:00')
date.append('06/09/2018 14:00')
date.append('06/09/2018 15:00')
date.append('06/09/2018 16:00')
date.append('06/09/2018 17:00')
date.append('06/09/2018 18:00')
date.append('06/09/2018 19:00')
date.append('06/09/2018 20:00')

# Interdisciplinary AB June 9 Microclimate Variables Data #

Int_AB_CHWTON = []
x = 15170
for i in range(16):
    Int_AB_CHWTON.append(Data_Inter['CHWTON'][i + x])
    x = x + 3

Int_AB_KW = []
x = 15170
for i in range(16):
    Int_AB_KW.append(Data_Inter['KW'][i + x])
    x = x + 3

Int_AB_June_9 = pd.DataFrame()
Int_AB_June_9['month'] = month
Int_AB_June_9['time'] = time
Int_AB_June_9['CHWTON'] = Int_AB_CHWTON
Int_AB_June_9['KW'] = Int_AB_KW
Int_AB_June_9['date'] = date
Int_AB_June_9['Air Temp'] = Inter_AB_W['Mean Air Temp']
Int_AB_June_9['Rel Humid'] = Inter_AB_W['Mean Rel Humidity']

Int_AB_June_9 = Int_AB_June_9.set_index(['date'])
#Int_AB_June_9


# Interdisciplinary AB June 9 AZW Variables Data #

AZW_June_9_Air_Temp = []

x = 15170
for i in range(16):
    AZW_June_9_Air_Temp.append(Data_Inter['Air Temp'][i + x])
    x = x + 3

AZW_June_9_Rel_Hum = []
    
x = 15170
for i in range(16):
    AZW_June_9_Rel_Hum.append(Data_Inter['Rel Humid'][i + x])
    x = x + 3

Int_AB_June_9_AZW = pd.DataFrame()
Int_AB_June_9_AZW['month'] = month
Int_AB_June_9_AZW['time'] = time
Int_AB_June_9_AZW['CHWTON'] = Int_AB_CHWTON
Int_AB_June_9_AZW['KW'] = Int_AB_KW
Int_AB_June_9_AZW['date'] = date
Int_AB_June_9_AZW['Air Temp'] = AZW_June_9_Air_Temp
Int_AB_June_9_AZW['Rel Humid'] = AZW_June_9_Rel_Hum

Int_AB_June_9_AZW = Int_AB_June_9_AZW.set_index(['date'])

In [6]:
Int_AB_June_9_AZW

                 month  time  CHWTON      KW  Air Temp  Rel Humid
date
06/09/2018 05:00    06  0500    2.08   93.54      27.0      14.84
06/09/2018 06:00    06  0600    1.22  117.23      26.0      15.74
06/09/2018 07:00    06  0700    1.36  103.66      28.0      17.42
06/09/2018 08:00    06  0800    2.67  106.36      31.0      11.78
06/09/2018 09:00    06  0900    2.71  105.26      33.0       9.06
06/09/2018 10:00    06  1000    3.53  103.63      35.0       7.52
06/09/2018 11:00    06  1100    4.02  105.14      37.0       6.74
06/09/2018 12:00    06  1200    5.69  103.65      39.0       5.19
06/09/2018 13:00    06  1300    4.84  105.62      41.0       4.32
06/09/2018 14:00    06  1400    4.79  102.44      41.0       3.99
06/09/2018 15:00    06  1500    4.76  107.61      42.0       4.10
06/09/2018 16:00    06  1600    5.34  100.95      42.0       3.79
06/09/2018 17:00    06  1700    5.51  107.19      42.0       3.79
06/09/2018 18:00    06  1800    4.22   82.90      42.0       4.10
06/09/2018 19:00    06  1900    4.64   93.02      40.0       5.74
06/09/2018 20:00    06  2000    3.16   91.26      38.0       6.38

In [7]:
Int_AB_June_9

                 month  time  CHWTON      KW   Air Temp  Rel Humid
date
06/09/2018 05:00    06  0500    2.08   93.54  29.537667  12.699708
06/09/2018 06:00    06  0600    1.22  117.23  29.033387  16.378229
06/09/2018 07:00    06  0700    1.36  103.66  29.604562  17.250977
06/09/2018 08:00    06  0800    2.67  106.36  31.459578  16.705515
06/09/2018 09:00    06  0900    2.71  105.26  33.820584  14.477529
06/09/2018 10:00    06  1000    3.53  103.63  35.796708  10.969304
06/09/2018 11:00    06  1100    4.02  105.14  36.879628   8.902718
06/09/2018 12:00    06  1200    5.69  103.65  37.837624   7.785688
06/09/2018 13:00    06  1300    4.84  105.62  38.771101   6.989491
06/09/2018 14:00    06  1400    4.79  102.44  39.486798   6.362558
06/09/2018 15:00    06  1500    4.76  107.61  39.867346   6.021546
06/09/2018 16:00    06  1600    5.34  100.95  40.046582   5.873886
06/09/2018 17:00    06  1700    5.51  107.19  39.936800   5.854970
06/09/2018 18:00    06  1800    4.22   82.90  39.575997   5.906207
06/09/2018 19:00    06  1900    4.64   93.02  38.936188   6.200171
06/09/2018 20:00    06  2000    3.16   91.26  38.108705   6.634349

In [8]:
######################### DROP June 9th Weather #####################
# row 15150 to row 15246 are all june 19th data
Data_Inter = Data_Inter.drop(Data_Inter.index[15150:15246])

In [9]:
# see if July 9th is gone
Data_Inter.iloc[15148:15155]

,month,time,bldgname,KW,CHWTON,HTmmBTU,Air Temp,Rel Humid
06/08/2018 23:30,06,2330,Interdisciplinary AB,92.50,2.18,0,33.0,9.77
06/08/2018 23:45,06,2345,Interdisciplinary AB,89.90,2.59,0,33.0,9.77
06/10/2018 00:00,06,0000,Interdisciplinary AB,89.21,2.24,0,33.0,7.21
06/10/2018 00:15,06,0015,Interdisciplinary AB,72.39,0.86,0,32.0,8.89
06/10/2018 00:30,06,0030,Interdisciplinary AB,73.41,1.07,0,33.0,7.79
06/10/2018 00:45,06,0045,Interdisciplinary AB,72.12,0.69,0,31.0,10.15
06/10/2018 01:00,06,0100,Interdisciplinary AB,73.12,0.77,0,31.0,10.94

In [10]:
Data_Inter

,month,time,bldgname,KW,CHWTON,HTmmBTU,Air Temp,Rel Humid
01/01/2018 00:00,01,0000,Interdisciplinary AB,138.33,1.09,0,11.0,40.24
01/01/2018 00:15,01,0015,Interdisciplinary AB,90.14,0.99,0,11.0,40.24
01/01/2018 00:30,01,0030,Interdisciplinary AB,80.49,1.01,0,10.0,43.01
01/01/2018 00:45,01,0045,Interdisciplinary AB,84.88,0.90,0,9.0,46.00
01/01/2018 01:00,01,0100,Interdisciplinary AB,85.83,0.87,0,9.0,46.00
...,...,...,...,...,...,...,...,...
12/31/2018 22:00,12,2200,Interdisciplinary AB,124.28,0.00,0,6.0,93.30
12/31/2018 22:15,12,2215,Interdisciplinary AB,127.61,0.00,0,5.0,100.00
12/31/2018 22:30,12,2230,Interdisciplinary AB,130.48,0.00,0,5.0,100.00
12/31/2018 22:45,12,2245,Interdisciplinary AB,133.01,0.00,0,6.0,93.30
12/31/2018 23:00,12,2300,Interdisciplinary AB,130.59,0.00,0,6.0,93.30

In [11]:
############################ RANDOM FORESTS #################################

## Set Dependent Variable
Y = Data_Inter['CHWTON']

## Set Independent Variables
X = Data_Inter.drop(labels = ['CHWTON', 'HTmmBTU', 'bldgname'], axis = 1)

## Setting up training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=20)

## Using RandomForestRegressor to make predictions
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, Y_train)

print("\033[1m" + "Model Accuracy = " + "\033[0m", model.score(X_test, Y_test),"\n")

## Get feature importance
feature_list = list(X.columns)
feature_imp = pd.Series(model.feature_importances_, index=feature_list).sort_values(ascending=False)
print("\033[1m" + "Feature Importances:" + "\033[0m")
print(feature_imp)

## Predictions
Y_pred = model.predict(X_test)
ModelPred = pd.DataFrame({'Actual CHWTON':Y_test, 'Predicted CHWTON':Y_pred})
ModelPred = ModelPred.sort_index()
print(ModelPred)

Model Accuracy =  0.9375325113008287

Feature Importances:
Air Temp     0.539095
month        0.251560
time         0.123080
KW           0.046700
Rel Humid    0.039565
dtype: float64
                  Actual CHWTON  Predicted CHWTON
01/01/2018 00:15           0.99            2.4567
01/01/2018 00:30           1.01            1.1853
01/01/2018 00:45           0.90            0.8790
01/01/2018 02:00           1.06            1.0406
01/01/2018 03:15           0.92            0.7523
...                         ...               ...
12/31/2018 17:30           0.00            0.0000
12/31/2018 18:45           0.00            0.0000
12/31/2018 22:15           0.00            0.0051
12/31/2018 22:45           0.00            0.0000
12/31/2018 23:00           0.00            0.0006

[6906 rows x 2 columns]

In [12]:
X.dtypes

month         object
time          object
KW           float64
Air Temp     float64
Rel Humid    float64
dtype: object

In [13]:
X

                 month  time      KW  Air Temp  Rel Humid
01/01/2018 00:00    01  0000  138.33      11.0      40.24
01/01/2018 00:15    01  0015   90.14      11.0      40.24
01/01/2018 00:30    01  0030   80.49      10.0      43.01
01/01/2018 00:45    01  0045   84.88       9.0      46.00
01/01/2018 01:00    01  0100   85.83       9.0      46.00
...                ...   ...     ...       ...        ...
12/31/2018 22:00    12  2200  124.28       6.0      93.30
12/31/2018 22:15    12  2215  127.61       5.0     100.00
12/31/2018 22:30    12  2230  130.48       5.0     100.00
12/31/2018 22:45    12  2245  133.01       6.0      93.30
12/31/2018 23:00    12  2300  130.59       6.0      93.30

[34527 rows x 5 columns]

In [14]:
X_int = X.drop(labels = ['month','time'], axis = 1)

In [15]:
from statsmodels.stats.outliers_influence import variance_inflation_factor 
vif_data = pd.DataFrame()
vif_data["feature"] = X_int.columns
vif_data["VIF"] = [variance_inflation_factor(X_int.values, i) for i in range(len(X_int.columns))]

In [16]:
vif_data

     feature       VIF
0         KW  6.620458
1   Air Temp  3.925219
2  Rel Humid  3.273488

In [17]:
# 1. Y data
# June 9 Actual CHWTON
Int_AB_June_9_Actual = pd.DataFrame()
Int_AB_June_9_Actual = Int_AB_June_9['CHWTON']

# 2. X data
## June 9 Baseline AZW Predictons (X) ##
Int_AB_June_9_AZW_Pred = pd.DataFrame()
Int_AB_June_9_AZW_Pred = Int_AB_June_9_AZW.drop(labels = ['CHWTON'], axis = 1)

## June 9 Microclimate Predictons (X) ##
Int_AB_June_9_Micro_Pred = pd.DataFrame()
Int_AB_June_9_Micro_Pred = Int_AB_June_9.drop(labels = ['CHWTON'], axis = 1)

# 3. Predict
June_9_Micro = model.predict(Int_AB_June_9_Micro_Pred)
June_9_AZW = model.predict(Int_AB_June_9_AZW_Pred)
Pred = pd.DataFrame({'Actual':Int_AB_June_9_Actual, 'Baseline Predictions (AZW)': June_9_AZW,
                     'Microclimate Predictions': June_9_Micro})

print(Pred)

                  Actual  Baseline Predictions (AZW)  Microclimate Predictions
date
06/09/2018 05:00    2.08                      1.5699                    2.0772
06/09/2018 06:00    1.22                      1.2949                    1.6508
06/09/2018 07:00    1.36                      1.9627                    2.2579
06/09/2018 08:00    2.67                      2.6334                    2.7723
06/09/2018 09:00    2.71                      2.5102                    3.3945
06/09/2018 10:00    3.53                      3.4021                    3.8262
06/09/2018 11:00    4.02                      4.1991                    4.1377
06/09/2018 12:00    5.69                      4.2883                    4.4807
06/09/2018 13:00    4.84                      4.9148                    4.6785
06/09/2018 14:00    4.79                      5.0062                    4.8188
06/09/2018 15:00    4.76                      5.4991                    5.0802
06/09/2018 16:00    5.34                      5.3752                    4.6935
06/09/2018 17:00    5.51                      5.4119                    4.8281
06/09/2018 18:00    4.22                      4.7283                    4.6225
06/09/2018 19:00    4.64                      4.8021                    4.8395
06/09/2018 20:00    3.16                      3.6996                    3.7188

In [18]:
Int_AB_June_9_AZW_Pred

                 month  time      KW  Air Temp  Rel Humid
date
06/09/2018 05:00    06  0500   93.54      27.0      14.84
06/09/2018 06:00    06  0600  117.23      26.0      15.74
06/09/2018 07:00    06  0700  103.66      28.0      17.42
06/09/2018 08:00    06  0800  106.36      31.0      11.78
06/09/2018 09:00    06  0900  105.26      33.0       9.06
06/09/2018 10:00    06  1000  103.63      35.0       7.52
06/09/2018 11:00    06  1100  105.14      37.0       6.74
06/09/2018 12:00    06  1200  103.65      39.0       5.19
06/09/2018 13:00    06  1300  105.62      41.0       4.32
06/09/2018 14:00    06  1400  102.44      41.0       3.99
06/09/2018 15:00    06  1500  107.61      42.0       4.10
06/09/2018 16:00    06  1600  100.95      42.0       3.79
06/09/2018 17:00    06  1700  107.19      42.0       3.79
06/09/2018 18:00    06  1800   82.90      42.0       4.10
06/09/2018 19:00    06  1900   93.02      40.0       5.74
06/09/2018 20:00    06  2000   91.26      38.0       6.38

In [19]:
# 4. Score
print("\033[1m" + "Accuracy using microclimate data = " + "\033[0m", model.score(Int_AB_June_9_Micro_Pred, Int_AB_June_9_Actual),"\n")
print("\033[1m" + "Accuracy using weather st. data = " + "\033[0m", model.score(Int_AB_June_9_AZW_Pred, Int_AB_June_9_Actual),"\n")

Accuracy using microclimate data =  0.8542406074167929

Accuracy using weather st. data =  0.8763692268362031

In [20]:
# June_9_Micro = model.predict(Int_AB_June_9_Micro_Pred)
# June_9_AZW = model.predict(Int_AB_June_9_AZW_Pred)
# Pred = pd.DataFrame({'Actual':Int_AB_June_9_Actual, 'Baseline Predictions (AZW)': June_9_AZW,
#                      'Microclimate Predictions': June_9_Micro})
from sklearn import metrics

print('RMSE (micro)', np.sqrt(metrics.mean_squared_error(Int_AB_June_9_Actual, June_9_Micro)),"\n")
print('RMSE (AZW)', np.sqrt(metrics.mean_squared_error(Int_AB_June_9_Actual, June_9_AZW)),"\n")

RMSE (micro) 0.5339284935738119

RMSE (AZW) 0.49173159726623217

In [21]:
####### Plotting Baseline Model for all 2018 15-min Data #######

### This is a big graph, will be slow to run but gives visual of prediction accuracy

%matplotlib qt
plt.xlabel('Baseline 15-Min Model')
plt.ylabel('CHWTON')
plt.plot(ModelPred['Actual CHWTON'], label = 'Actual CHWT')
plt.plot(ModelPred['Predicted CHWTON'], label = 'Predicted CHWT')
plt.legend()
plt.show()

ImportError: Failed to import any qt binding

In [ ]:
####### Plotting ENVI-met vs AZW vs Actual Data for June 9 from 5a - 8p #######

%matplotlib qt

positions = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
labels = ['5a', '6a', '7a', '8a', '9a', '10a', '11a', '12p', '1p', '2p', '3p', '4p', '5p', '6p', '7p', '8p']

##plot EnviMet vs AZ_Weather results
plt.xlabel('Time 5a - 8p')
plt.ylabel('CHWTON')
plt.xticks(positions, labels)
plt.plot(Pred['Microclimate Predictions'], label = 'ENVIMET Weather')
plt.plot(Pred['Baseline Predictions (AZW)'], label = 'Baseline Weather (AZW)')
plt.plot(Pred['Actual'], label = 'Actual Data')
plt.title('Interdisciplinary AB')
plt.legend()
## show graphs
plt.show()