In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import re

import pathlib

In [19]:
year = ['2017', '2018', '2019', '2020']
    
path_name = "./Data/ASU_weather/x-weather(" + year[2] + ").csv"
asu_weather = pd.read_csv(path_name)
    
# get year
asu_weather["Date and Time"] = pd.to_datetime(asu_["Date and Time"])
asu_weather["year"] = asu_["Date and Time"].dt.year

# remove wrong year
asu_weather = asu_weather[asu_weather["year"] == int(year[2])]
    
# remove year and unnamed column
asu_weather = asu_weather.iloc[: , :-2]
    
# rename column
new_column = ['Date_Time', 'Dew', 'Air Temp', 'Rel Humid', 'Solar Rad', 'Wind']
asu_weather.set_axis(new_column, axis =1, inplace = True)

# choose column
asu_weather = asu_weather[['Date_Time','Air Temp', 'Rel Humid']]

In [20]:
asu_weather

                Date_Time  Air Temp  Rel Humid
0     2019-01-01 00:00:00      40.2       90.9
1     2019-01-01 00:15:00      40.1       91.2
2     2019-01-01 00:30:00      40.3       91.5
3     2019-01-01 00:45:00      40.4       91.5
4     2019-01-01 01:00:00      40.4       91.6
...                   ...       ...        ...
35035 2019-12-31 22:45:00      46.7       57.6
35036 2019-12-31 23:00:00      46.0       64.3
35037 2019-12-31 23:15:00      44.9       67.1
35038 2019-12-31 23:30:00      44.8       70.3
35039 2019-12-31 23:45:00      45.0       70.7

[35040 rows x 3 columns]